version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/base.nginx:/etc/nginx/nginx.conf
      - ./docker/nginx/log:/var/log/nginx/
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini

  mysql:
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./docker/mysql/data:/var/lib/mysql
